const GET_MOVIES = 'GET_MOVIES';
const GET_MOVIES_DETAIL = 'GET_MOVIE_DETAIL';
const ADD_MOVIE_FAVORITE = 'ADD_MOVIE_FAVORITE';
const REMOVE_MOVIE_FAVORITE = 'REMOVE_MOVIE_FAVORITE'

module.exports = {
    GET_MOVIES,
    GET_MOVIES_DETAIL,
    ADD_MOVIE_FAVORITE,
    REMOVE_MOVIE_FAVORITE
}